---
- name: Reload sysctl
  ansible.builtin.command:
    cmd: sysctl --system

- name: Restart fail2ban
  ansible.builtin.systemd:
    name: fail2ban
    state: restarted

- name: Restart resolved
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted
